-- ============================================================================
-- BIOLOG — Official Business Trip (ROBT) requests
-- ----------------------------------------------------------------------------
-- IMAGE-FIRST. The signatories (Employee, Department Head, HRAD) sign on
-- PAPER, so the signed form is captured as a photo and that photo is the
-- approval artifact. There are deliberately NO signature columns here.
--
-- APPROVAL CHAIN TODAY:  Agent -> HRAD
--   A Department Head signature on the paper form is not a second gate in the
--   app, and there is no COO step yet. HRAD is the only approver
--   (can_review_ob in lib/rbac.ts).
--
--   'For COO Approval' is kept in the Status CHECK as a RESERVED value: nothing
--   writes it and no transition targets it. When COO sign-off for late filings
--   lands, add it to OB_REVIEW_ACTIONS in lib/ob-requests.ts plus an Escalate
--   button — no migration is needed for that.
--
-- WHEN THIS CHANGES
--   Once digital signatories are solved, add the full digital form fields plus
--   an e-signature pad, drop the NOT NULL on "PhotoURL", and make the image an
--   optional supporting attachment instead of the source of truth.
--
-- HOW TO APPLY
--   Supabase Dashboard -> SQL Editor -> paste -> Run.
--   Every statement is idempotent (IF NOT EXISTS), so re-running is safe.
--
-- WHY company_id IS NULLABLE
--   Same reasoning as 20260101_admin_platform.sql: the column is added with no
--   backfill and no NOT NULL so nothing existing breaks. API routes filter on
--   company_id only when the caller's row actually has one, so an un-backfilled
--   install keeps working instead of silently returning zero rows.
-- ============================================================================


-- ── STEP 1 · the table ─────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.ob_requests (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Who filed it. "ReferenceID" is the users-table key used everywhere else in
  -- this schema (tasklog, gps_reports); the rest are snapshots copied at submit
  -- time so history still reads correctly after someone changes department.
  "ReferenceID"   text NOT NULL,
  "Name"          text,
  "Position"      text,
  "Department"    text,

  -- The few optional details that let an admin filter without opening the image.
  "Destination"   text,
  "DateOfOB"      date,
  "PurposeOfTravel" text,

  -- Late filing = filed with <= 1 day of notice. Guideline 3 of the form asks
  -- for a justification in that case; HRAD decides on it. The flag is
  -- recomputed server-side on insert, never trusted from the client.
  "IsLateFiling"  boolean NOT NULL DEFAULT false,
  "Justification" text,

  -- REQUIRED. Array of image URLs, same shape as gps_reports.PhotoURL.
  -- jsonb so the viewer and the exporter can treat it as a list without parsing.
  "PhotoURL"      jsonb NOT NULL DEFAULT '[]'::jsonb,

  "Status"        text NOT NULL DEFAULT 'Pending Review'
                  CHECK ("Status" IN ('Pending Review','Approved','Declined',
                                      'For COO Approval')),

  -- Written by the server from the session, never from the request body.
  "ReviewedBy"    text,
  "ReviewNotes"   text,
  "ReviewedAt"    timestamptz,

  date_created    timestamptz NOT NULL DEFAULT now(),
  company_id      bigint,

  -- An OB request with no photo cannot be approved on paper-signature grounds,
  -- so keep the invariant in the database rather than trusting the client.
  CONSTRAINT ob_requests_photo_required
    CHECK (jsonb_typeof("PhotoURL") = 'array' AND jsonb_array_length("PhotoURL") > 0)
);

-- Every read path filters on company_id, then sorts by newest first.
CREATE INDEX IF NOT EXISTS idx_ob_requests_company
  ON public.ob_requests (company_id);

CREATE INDEX IF NOT EXISTS idx_ob_requests_reference
  ON public.ob_requests ("ReferenceID", date_created DESC);

-- The admin queue is "pending, newest first", and the "Late Filing" filter
-- scans on IsLateFiling.
CREATE INDEX IF NOT EXISTS idx_ob_requests_status
  ON public.ob_requests ("Status", date_created DESC);

CREATE INDEX IF NOT EXISTS idx_ob_requests_late
  ON public.ob_requests ("IsLateFiling")
  WHERE "IsLateFiling" = true;


-- ── STEP 2 · company FK ────────────────────────────────────────────────────

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'ob_requests_company_id_fkey'
  ) THEN
    ALTER TABLE public.ob_requests
      ADD CONSTRAINT ob_requests_company_id_fkey
      FOREIGN KEY (company_id)
      REFERENCES public.companies (id) ON DELETE SET NULL;
  END IF;
END $$;


-- ── STEP 3 · storage bucket (OPTIONAL) ─────────────────────────────────────
-- lib/storage.ts uploads to Supabase FIRST and silently falls back to
-- Cloudinary if this bucket is missing, so the feature works before you run
-- this. Create the bucket here to switch storage over — no code change needed.
--
-- The bucket is PUBLIC because the agent app renders these URLs with the anon
-- key in plain <img> tags and there is no signed-URL helper in this codebase.
-- That is acceptable for the same reason gps_reports.PhotoURL is: the URLs are
-- unguessable object paths, and every READ of the row is still RBAC-gated in
-- pages/api/ob-request.ts. If you later move to a private bucket, add
-- `createSignedUrl` in the viewer and make the bucket private.

-- INSERT INTO storage.buckets (id, name, public)
--   VALUES ('ob-requests', 'ob-requests', true)
--   ON CONFLICT (id) DO NOTHING;

-- Allow the anon key to upload into that bucket. Everything else stays denied.
-- CREATE POLICY "ob_requests_upload" ON storage.objects
--   FOR INSERT TO anon, authenticated
--   WITH CHECK (bucket_id = 'ob-requests');

-- Public read of the objects themselves.
-- CREATE POLICY "ob_requests_read" ON storage.objects
--   FOR SELECT TO anon, authenticated
--   USING (bucket_id = 'ob-requests');


-- ── STEP 4 · backfill company_id (OPTIONAL) ────────────────────────────────
-- Only after STEP 3 of the admin_platform migration has run:
--
--   UPDATE public.ob_requests SET company_id = (SELECT id FROM public.companies LIMIT 1);


-- ── STEP 5 · RLS note ──────────────────────────────────────────────────────
-- Same posture as the rest of the app: the ANON key reaches these tables and
-- all authorization happens in API routes. Enabling RLS without policies would
-- make the OB screens return empty lists rather than errors, which is much
-- harder to debug than an explicit 401.
--
--   REVOKE ALL ON public.ob_requests FROM anon;