-- ============================================================================
-- BIOLOG — Group Visitation (team-restricted)
-- ----------------------------------------------------------------------------
-- A field agent joins a manager/TSM's visit to a company, or creates one and
-- invites their own team.
--
-- WHY THE VISIBILITY RULE LIVES HERE
--   Visibility is a property of the CREATOR, not the visitor:
--     creator is a Manager / Territory Sales Manager / TSM
--       -> defaults to team_only, with an "Allow other teams to join?" override
--     creator is an ordinary agent (TSA / User / etc.)
--       -> defaults to open_to_all, with a "Team only?" override
--   Team membership is resolved from users.TSM / users.Manager (by
--   ReferenceID) and, as a fallback, users.TSMName / users.ManagerName (by
--   full name) — see lib/group-visits.ts, which is the single authority.
--
-- WHY EACH MEMBER IS A ROW
--   Membership drives the avatar stack, the "N of M joined" count, the leave
--   button and the creator's notifications, so it is real state rather than a
--   jsonb array.
--
-- HOW TO APPLY
--   Supabase Dashboard -> SQL Editor -> paste -> Run. Idempotent.
-- ============================================================================


-- ── STEP 1 · group_visitations ────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.group_visitations (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Creator. Deliberately NOT a hard FK to users.ReferenceID: that column has
  -- no unique constraint on every install (see lib/group-visits.ts), and a
  -- failed FK would make the whole feature unusable rather than just a warning.
  "ReferenceID_creator" text NOT NULL,

  -- Snapshotted so a later role change can't retroactively rewrite who an old
  -- group visit was restricted to.
  "CreatorRole"      text,
  "CreatorName"      text,

  -- The company being visited — the headline of every card.
  "CompanyName"      text NOT NULL,
  "CompanyAddress"   text,

  "VisitDate"        date NOT NULL DEFAULT current_date,
  "MeetupTime"       time,
  "MeetingPoint"     text,
  "Purpose"          text,

  -- NULL = unlimited.
  "MaxMembers"       int CHECK ("MaxMembers" IS NULL OR "MaxMembers" > 0),

  "Visibility"       text NOT NULL DEFAULT 'team_only'
                      CHECK ("Visibility" IN ('team_only','open_to_all')),

  "Status"           text NOT NULL DEFAULT 'Upcoming'
                      CHECK ("Status" IN ('Upcoming','Ongoing','Completed','Cancelled')),

  "GroupPhotoURL"    text,

  date_created       timestamptz NOT NULL DEFAULT now(),
  company_id         bigint,

  CONSTRAINT group_visitations_company_required
    CHECK (btrim("CompanyName") <> '')
);

CREATE INDEX IF NOT EXISTS idx_gv_visit_date  ON public.group_visitations ("VisitDate", date_created DESC);
CREATE INDEX IF NOT EXISTS idx_gv_creator     ON public.group_visitations ("ReferenceID_creator");
CREATE INDEX IF NOT EXISTS idx_gv_visibility  ON public.group_visitations ("Visibility");
CREATE INDEX IF NOT EXISTS idx_gv_company     ON public.group_visitations (company_id);
CREATE INDEX IF NOT EXISTS idx_gv_open_feed   ON public.group_visitations (date_created DESC)
  WHERE "Visibility" = 'open_to_all';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'group_visitations_company_id_fkey'
  ) THEN
    ALTER TABLE public.group_visitations
      ADD CONSTRAINT group_visitations_company_id_fkey
      FOREIGN KEY (company_id)
      REFERENCES public.companies (id) ON DELETE CASCADE;
  END IF;
END $$;


-- ── STEP 2 · group_visit_members ──────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.group_visit_members (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_visit_id   bigint NOT NULL REFERENCES public.group_visitations (id) ON DELETE CASCADE,
  "ReferenceID"    text NOT NULL,
  joined_at        timestamptz NOT NULL DEFAULT now(),
  -- "Check in together": marks the member present at the meet-up. Kept on the
  -- membership row rather than tasklog so the group can be audited on its own.
  checked_in       boolean NOT NULL DEFAULT false,
  checked_in_at    timestamptz,

  -- One membership per person per visit — enforced here rather than in the API
  -- so a double-tap can't create a duplicate.
  CONSTRAINT group_visit_members_unique UNIQUE (group_visit_id, "ReferenceID")
);

CREATE INDEX IF NOT EXISTS idx_gvm_visit     ON public.group_visit_members (group_visit_id);
CREATE INDEX IF NOT EXISTS idx_gvm_reference ON public.group_visit_members ("ReferenceID");


-- ── STEP 3 · link to attendance ───────────────────────────────────────────
-- The spec asks for `ALTER TABLE public.site_visits ADD COLUMN group_visit_id`.
-- public.site_visits DOES NOT EXIST in this project: attendance and client
-- visits both live in public.tasklog (see 20260101_admin_platform.sql, which
-- notes this explicitly). So there is nothing to alter — "Check in together"
-- therefore records attendance through tasklog's Type/SiteVisitAccount and
-- tags it with "GV:<id>" rather than adding an orphaned FK.
--
-- If site_visits is ever created, add:
--
--   ALTER TABLE public.site_visits ADD COLUMN IF NOT EXISTS group_visit_id bigint
--     REFERENCES public.group_visitations (id) ON DELETE SET NULL;


-- ── STEP 4 · notification type for group visits ───────────────────────────
-- public.notifications.type has a CHECK that predates this feature, so a group
-- visit notification cannot be inserted until 'group_visit' is allowed.
--
-- Reusing an existing type was rejected deliberately: 'ob_submitted' is what
-- drives the ADMIN bell (lib/notifications.ts ADMIN_BELL_TYPES), so filing
-- group visits under it would push "New group visit" cards into the OB Approvals
-- queue and hide real OB requests among them.

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'notifications_type_check'
  ) THEN
    ALTER TABLE public.notifications DROP CONSTRAINT notifications_type_check;
    ALTER TABLE public.notifications
      ADD CONSTRAINT notifications_type_check
      CHECK (type IN ('ob_approved','ob_declined','ob_submitted','gps_reviewed','group_visit'));
    RAISE NOTICE 'notifications.type now accepts group_visit';
  ELSE
    RAISE NOTICE 'notifications_type_check already exists — verify it allows ''group_visit''';
  END IF;
END $$;


-- ── STEP 5 · RLS note ─────────────────────────────────────────────────────
-- Same posture as the rest of the app: the ANON key reaches these tables and
-- every read and write is authorised in pages/api/group-visits*.ts.
-- Restricting a group visit is ENFORCED THERE, not by a policy — a Postgres RLS
-- rule cannot express "is this viewer under that group's creator", because the
-- creator lives on the other table.
--
--   REVOKE ALL ON public.group_visitations, public.group_visit_members FROM anon;