-- ============================================================================
-- BIOLOG — Website contact submissions
-- ----------------------------------------------------------------------------
-- Backs the marketing site form at /website/contact.html.
--
-- ----------------------------------------------------------------------------
-- WHY A TABLE AND NOT JUST AN EMAIL
-- A marketing form that only emails is a form you lose. Email bounces, filters
-- and archives; a demo request sitting in someone's inbox in 2027 is gone. This
-- table makes a submission durable, queryable by status, and included in the
-- same JSON backup as everything else — so it survives a bad deploy.
--
-- It also means the admin can triage without reading mail: New → Contacted →
-- Closed, with an owner and a note, which is how a real lead pipeline works.
--
-- ----------------------------------------------------------------------------
-- THIS IS THE ONLY PLACE PERSONAL DATA ENTERS THE SYSTEM
-- Name, work email, company, message, user count, and the IP/UA of the
-- submission. Two consequences worth stating plainly:
--   * The website is PUBLIC. This table is written by anonymous callers, so it
--     must never contain anything an admin should not see in a shared export.
--   * submitted_ip and user_agent are kept for spam triage ONLY. They are NOT
--     in the backup manifest on purpose: an IP address identifies a person, and
--     a backup file gets emailed around. The owner, status and notes — the
--     parts a pipeline actually needs — are all included.
--
-- ----------------------------------------------------------------------------
-- SPAM
-- There is no CAPTCHA. That is a deliberate trade-off, documented rather than
-- hidden: a captcha on a demo-request form loses more legitimate Philippine
-- field-team leads than it stops bots, because the whole audience is on mobile
-- data. The defences are instead (a) per-IP rate limiting in the API route, and
-- (b) a honeypot field, and (c) length caps enforced by CHECKs below, which
-- alone make a naive bulk-submit script fail. If this ever gets hammered, add
-- Cloudflare Turnstile on the form — do NOT reach for a checkbox captcha.
--
-- HOW TO APPLY
--   Supabase Dashboard -> SQL Editor -> paste -> Run. Idempotent.
--   Until this is applied, POST /api/public/website-inquiry returns 200 with
--   { ok: true, stored: false } and logs a warning: the visitor still sees
--   their confirmation, and the admin page says the table is missing.
-- ============================================================================


-- ── STEP 1 · the table ──────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.website_inquiries (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  name            text NOT NULL CHECK (btrim(name) <> '' AND length(name) <= 120),
  email           text NOT NULL CHECK (btrim(email) <> '' AND length(email) <= 200),
  company         text          CHECK (company IS NULL OR length(company) <= 160),
  message         text          CHECK (message IS NULL OR length(message) <= 4000),

  -- The form offers fixed ranges rather than a free number, so this is a
  -- label ("11-50") and not a count. A number here would be wrong the moment
  -- someone types "about 40".
  user_range      text CHECK (user_range IS NULL OR length(user_range) <= 40),

  -- Pipeline. The admin page filters on these, so they are constrained values
  -- and not free text.
  status          text NOT NULL DEFAULT 'new'
                    CHECK (status IN ('new','contacted','closed','spam')),
  -- Which salesperson picked it up.
  assigned_to     text,
  -- A short note about the call. Not the message itself.
  notes           text CHECK (notes IS NULL OR length(notes) <= 2000),

  -- Provenance, for spam triage only. Deliberately excluded from the backup.
  submitted_ip    text CHECK (submitted_ip IS NULL OR length(submitted_ip) <= 64),
  user_agent      text CHECK (user_agent IS NULL OR length(user_agent) <= 400),
  -- Which page the visitor was on. Useful to know a pricing-page enquiry is
  -- warmer than a footer one.
  source_page     text CHECK (source_page IS NULL OR length(source_page) <= 200),
  -- Honeypot: if this is non-empty the submission was a bot. The API rejects
  -- it before the insert, so a non-null value here means someone changed that.
  -- Kept as a column so the check is inspectable rather than implicit.
  honeypot        text,

  is_read         boolean NOT NULL DEFAULT false,
  read_at         timestamptz,

  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),

  -- Multi-tenant, NULL for the public site (which has no tenant context).
  company_id      bigint
);

-- The admin queue's only query: unread first, then newest.
CREATE INDEX IF NOT EXISTS idx_website_inquiries_queue
  ON public.website_inquiries (is_read, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_website_inquiries_status
  ON public.website_inquiries (status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_website_inquiries_email
  ON public.website_inquiries (lower(email));

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'website_inquiries_company_id_fkey'
  ) THEN
    ALTER TABLE public.website_inquiries
      ADD CONSTRAINT website_inquiries_company_id_fkey
      FOREIGN KEY (company_id)
      REFERENCES public.companies (id) ON DELETE SET NULL;
  END IF;
END $$;


-- ── STEP 2 · weekly volume view ─────────────────────────────────────────────
-- "How many demo requests came in this week" is the only question anyone asks
-- of this table, so it is answered here once rather than re-derived in the UI.

CREATE OR REPLACE VIEW public.v_website_inquiry_stats AS
SELECT
  date_trunc('week', created_at)::date                AS week_start,
  count(*)::int                                       AS total,
  count(*) FILTER (WHERE status = 'new')::int          AS new_count,
  count(*) FILTER (WHERE status = 'contacted')::int    AS contacted_count,
  count(*) FILTER (WHERE status = 'closed')::int       AS closed_count,
  count(*) FILTER (WHERE status = 'spam')::int         AS spam_count,
  count(*) FILTER (WHERE NOT is_read)::int             AS unread_count
FROM public.website_inquiries
GROUP BY 1;


-- ── STEP 3 · verification ───────────────────────────────────────────────────
-- After Step 1 (and BEFORE any real submission, since the API degrades quietly
-- when the table is missing):
--
--   -- expect 1
--   SELECT count(*) FROM information_schema.tables
--    WHERE table_schema='public' AND table_name='website_inquiries';
--
--   -- a long message must be refused by the CHECK, not silently truncated
--   INSERT INTO public.website_inquiries (name, email, message)
--   VALUES ('Test', 't@example.com', repeat('x', 5000));
--   -- expect: ERROR  new row violates check constraint
--
--   -- delete the test row afterwards
--   DELETE FROM public.website_inquiries WHERE email = 't@example.com';
--
--   -- once submissions exist
--   SELECT week_start, total, new_count, unread_count
--     FROM public.v_website_inquiry_stats ORDER BY week_start DESC;
--
-- ----------------------------------------------------------------------------
-- ADD IT TO THE BACKUP — ONE LINE
-- This table is deliberately listed in lib/backup-manifest.ts WITHOUT
-- submitted_ip, user_agent or honeypot. If you re-add it there, keep those
-- three out: they identify the visitor and have no business in a file that gets
-- emailed around.
--
-- ----------------------------------------------------------------------------
-- NO RLS — same reasoning as every other migration in this repository. The
-- write route is public by necessity and validates every field; the read and
-- update routes require a session with can_manage_settings and re-check it on
-- every call. An RLS pass over this one table in isolation would be theatre.
-- ============================================================================