-- ============================================================================
-- BIOLOG — email configuration + in-app notifications
-- ----------------------------------------------------------------------------
-- Adds three things on top of the OB request work:
--   1. public.email_config   — per-company outbound mail settings
--   2. public.notifications  — in-app bell (admin: OB approvals; agent: OB status)
--   3. email-tracking columns on public.ob_requests
--
-- HOW TO APPLY
--   Supabase Dashboard -> SQL Editor -> paste -> Run.
--   Idempotent throughout (IF NOT EXISTS / ON CONFLICT), so re-running is safe.
-- ============================================================================


-- ── STEP 1 · email_config ──────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.email_config (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- One row per company. The app filters on this; NULL means "the default
  -- install", which is what a single-tenant deployment looks like.
  company_id    bigint,

  -- AES-256-GCM ciphertext, produced by lib/secret-box.ts. NEVER the plaintext:
  -- this is a live credential that can send mail as the company. The API masks
  -- it on read and treats it as write-only from the UI.
  resend_api_key_enc text,

  sender_email  text,
  sender_name   text,

  -- JSON string arrays. A company may have several HRAD addresses on one form.
  ob_recipients   jsonb NOT NULL DEFAULT '[]'::jsonb,
  gps_recipients  jsonb NOT NULL DEFAULT '[]'::jsonb,
  timesheet_recipients jsonb NOT NULL DEFAULT '[]'::jsonb,

  -- Subject/body for the "new OB request" mail to HRAD.
  ob_subject_template text,
  ob_body_template    text,

  -- Send a mail to HRAD automatically on every OB submit. Off by default: an
  -- admin should opt in once they have confirmed the addresses.
  auto_send_on_ob  boolean NOT NULL DEFAULT false,

  is_active      boolean NOT NULL DEFAULT true,
  updated_at     timestamptz NOT NULL DEFAULT now(),
  created_at     timestamptz NOT NULL DEFAULT now(),

  -- A recipient list is only ever addresses.
  CONSTRAINT email_config_ob_recipients_array
    CHECK (jsonb_typeof(ob_recipients) = 'array'),
  CONSTRAINT email_config_gps_recipients_array
    CHECK (jsonb_typeof(gps_recipients) = 'array')
);

-- Uniqueness: one row per company, PLUS one row for the NULL "default install".
--
-- A plain UNIQUE (company_id) is NOT sufficient: NULLs never compare equal, so
-- it would permit any number of default rows.
--
-- The two PARTIAL indexes below are what enforce both halves. They also mean
-- `upsert(..., { onConflict: 'company_id' })` CANNOT work — Postgres will only
-- use a partial index for ON CONFLICT if the WHERE predicate is restated in the
-- conflict target, which PostgREST's onConflict option cannot express. Expect
-- error 42P10 if you try. lib/email-config.ts therefore does read-then-write by
-- primary key instead.
--
-- These are UNIQUE INDEXes, not constraints, so if you ever switch to a real
-- ON CONFLICT you would need `onConflict: 'company_id,nulls_first'` semantics
-- or a different constraint shape.
CREATE UNIQUE INDEX IF NOT EXISTS idx_email_config_company
  ON public.email_config (company_id)
  WHERE company_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_email_config_default
  ON public.email_config ((true))
  WHERE company_id IS NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'email_config_company_id_fkey'
  ) THEN
    ALTER TABLE public.email_config
      ADD CONSTRAINT email_config_company_id_fkey
      FOREIGN KEY (company_id)
      REFERENCES public.companies (id) ON DELETE CASCADE;
  END IF;
END $$;


-- ── STEP 2 · notifications ─────────────────────────────────────────────────

-- One row per recipient. There is deliberately no "broadcast" row: the admin
-- bell shows only that recipient's items, so an unread count can never leak one
-- reviewer's queue into another's.
CREATE TABLE IF NOT EXISTS public.notifications (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Recipient. For an agent this is their users.ReferenceID; for a reviewer
  -- notification it is also a ReferenceID (one row inserted per reviewer).
  "ReferenceID" text NOT NULL,

  type         text NOT NULL
               CHECK (type IN ('ob_approved','ob_declined','ob_submitted',
                               'gps_reviewed')),

  title        text NOT NULL,
  message      text,
  -- Where the bell item navigates to, e.g. /admin/ob-approvals or
  -- /ob-request?id=<userId>.
  link_url     text,

  -- The admin bell renders a thumbnail; for ob_submitted this is
  -- [first PhotoURL] of the request.
  thumb_url    text,

  -- Extra context (destination, status, reason) so the dropdown can render
  -- without a second round trip.
  meta         jsonb NOT NULL DEFAULT '{}'::jsonb,

  is_read      boolean NOT NULL DEFAULT false,
  read_at      timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now(),
  company_id   bigint
);

CREATE INDEX IF NOT EXISTS idx_notifications_recipient
  ON public.notifications ("ReferenceID", created_at DESC);

-- The bell query is always "my unread, newest first", so a partial index on
-- is_read = false keeps it off the table once items are read.
CREATE INDEX IF NOT EXISTS idx_notifications_unread
  ON public.notifications ("ReferenceID", created_at DESC)
  WHERE is_read = false;

CREATE INDEX IF NOT EXISTS idx_notifications_company
  ON public.notifications (company_id);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'notifications_company_id_fkey'
  ) THEN
    ALTER TABLE public.notifications
      ADD CONSTRAINT notifications_company_id_fkey
      FOREIGN KEY (company_id)
      REFERENCES public.companies (id) ON DELETE CASCADE;
  END IF;
END $$;


-- ── STEP 3 · email tracking on ob_requests ─────────────────────────────────

-- Lets the admin see, per request, whether HRAD was actually reached. The
-- warning banner in OB Approvals reads EmailStatus = 'failed'.
ALTER TABLE public.ob_requests ADD COLUMN IF NOT EXISTS "EmailStatus"  text;
ALTER TABLE public.ob_requests ADD COLUMN IF NOT EXISTS "EmailSentAt"  timestamptz;
ALTER TABLE public.ob_requests ADD COLUMN IF NOT EXISTS "EmailRetries" int NOT NULL DEFAULT 0;
ALTER TABLE public.ob_requests ADD COLUMN IF NOT EXISTS "EmailError"   text;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'ob_requests_email_status_check'
  ) THEN
    ALTER TABLE public.ob_requests
      ADD CONSTRAINT ob_requests_email_status_check
      CHECK ("EmailStatus" IS NULL OR "EmailStatus" IN ('pending','sent','failed'));
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_ob_requests_email_failed
  ON public.ob_requests (date_created DESC)
  WHERE "EmailStatus" = 'failed';


-- ── STEP 4 · realtime (OPTIONAL) ───────────────────────────────────────────
-- The bell polls every 30s by default, which needs nothing here. To switch to
-- Supabase Realtime instead, enable publication on this table:
--
--   ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications;
--
-- The anon key reaches this table and all authorisation happens in
-- pages/api/notifications.ts, same as the rest of the app. Revoke anon access
-- if you ever expose this publicly — but note the client talks to PostgREST
-- through our API routes, not directly.
--
--   REVOKE ALL ON public.notifications FROM anon;